version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.ApplicationInsights.AspNetCore
    versions:
    - 2.16.0
  - dependency-name: AutoMapper.Extensions.Microsoft.DependencyInjection
    versions:
    - 8.1.0
  - dependency-name: Microsoft.Rest.ClientRuntime
    versions:
    - 2.3.22
